export const URIs = [{
  label: "commons",
  list: [
    { scheme: "http", template: "", description: "Hypertext Transfer Protocol", status: "Permanent", support: "[RFC8615]", abempty: true, ref: "[RFC7230, Section 2.7.1]", notes: "" },
    { scheme: "https", template: "", description: "Hypertext Transfer Protocol Secure", status: "Permanent", support: "[RFC8615]", abempty: true, ref: "[RFC7230, Section 2.7.2]", notes: "" },
    { scheme: "tel", template: "", description: "telephone", status: "Permanent", support: "-", ref: "[RFC3966][RFC5341]", notes: "" }],
}, {
  label: "others",
  list: [
    { scheme: "aaa", template: "", description: "Diameter Protocol", status: "Permanent", support: "-", ref: "[RFC6733]", notes: "" },
    { scheme: "aaas", template: "", description: "Diameter Protocol with Secure Transport", status: "Permanent", support: "-", ref: "[RFC6733]", notes: "" },
    { scheme: "about", template: "", description: "about", status: "Permanent", support: "-", ref: "[RFC6694]", notes: "" },
    { scheme: "acap", template: "", description: "application configuration access protocol", status: "Permanent", support: "-", ref: "[RFC2244]", notes: "" },
    { scheme: "acct", template: "", description: "acct", status: "Permanent", support: "-", ref: "[RFC7565]", notes: "" },
    { scheme: "acd", template: "prov/acd", description: "acd", status: "Provisional", support: "-", ref: "[Michael_Hedenus]", notes: "" },
    { scheme: "acr", template: "prov/acr", description: "acr", status: "Provisional", support: "-", ref: "[OMA-OMNA]", notes: "" },
    { scheme: "adiumxtra", template: "prov/adiumxtra", description: "adiumxtra", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "adt", template: "prov/adt", description: "adt", status: "Provisional", support: "-", ref: "[SAP_SE]", notes: "" },
    { scheme: "afp", template: "prov/afp", description: "afp", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "afs", template: "", description: "Andrew File System global file names", status: "Provisional", support: "-", ref: "[RFC1738]", notes: "" },
    { scheme: "aim", template: "prov/aim", description: "aim", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "amss", template: "prov/amss", description: "amss", status: "Provisional", support: "-", ref: "[RadioDNS_Project]", notes: "" },
    { scheme: "android", template: "prov/android", description: "android", status: "Provisional", support: "-", ref: "[Adam_Barth][https://developer.android.com/guide/topics/manifest/manifest-intro]", notes: "" },
    { scheme: "appdata", template: "prov/appdata", description: "appdata", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "apt", template: "prov/apt", description: "apt", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "ark", template: "prov/ark", description: "ark", status: "Provisional", support: "-", ref: "[ARK_agency][https://n2t.net/ark:/21206/10015]", notes: "" },
    { scheme: "attachment", template: "prov/attachment", description: "attachment", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "aw", template: "prov/aw", description: "aw", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "barion", template: "prov/barion", description: "barion", status: "Provisional", support: "-", ref: "[Bíró_Tamás]", notes: "" },
    { scheme: "beshare", template: "prov/beshare", description: "beshare", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "bitcoin", template: "prov/bitcoin", description: "bitcoin", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "bitcoincash", template: "prov/bitcoincash", description: "bitcoincash", status: "Provisional", support: "-", ref: "[Corentin_Mercier]", notes: "" },
    { scheme: "blob", template: "prov/blob", description: "blob", status: "Provisional", support: "-", ref: "[W3C_WebApps_Working_Group][Chris_Rebert]", notes: "" },
    { scheme: "bolo", template: "prov/bolo", description: "bolo", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "browserext", template: "prov/browserext", description: "browserext", status: "Provisional", support: "-", ref: "[Mike_Pietraszak]", notes: "" },
    { scheme: "cabal", template: "prov/cabal", description: "cabal", status: "Provisional", support: "-", ref: "[Frédéric_Wang][Cabal_Club]", notes: "" },
    { scheme: "calculator", template: "prov/calculator", description: "calculator", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "callto", template: "prov/callto", description: "callto", status: "Provisional", support: "-", ref: "[Alexey_Melnikov]", notes: "" },
    { scheme: "cap", template: "", description: "Calendar Access Protocol", status: "Permanent", support: "-", ref: "[RFC4324]", notes: "" },
    { scheme: "cast", template: "prov/cast", description: "cast", status: "Provisional", support: "-", ref: "[Adam_Barth][https://developers.google.com/cast/docs/registration]", notes: "" },
    { scheme: "casts", template: "prov/casts", description: "casts", status: "Provisional", support: "-", ref: "[Adam_Barth][https://developers.google.com/cast/docs/registration]", notes: "" },
    { scheme: "chrome", template: "prov/chrome", description: "chrome", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "chrome-extension", template: "prov/chrome-extension", description: "chrome-extension", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "cid", template: "", description: "content identifier", status: "Permanent", support: "-", ref: "[RFC2392]", notes: "" },
    { scheme: "coap", template: "", description: "coap", status: "Permanent", support: "[RFC7252]", ref: "[RFC7252]", notes: "" },
    { scheme: "coap+tcp", template: "", description: "coap+tcp [1]", status: "Permanent", support: "[RFC8323]", ref: "[RFC8323]", notes: "" },
    { scheme: "coap+ws", template: "", description: "coap+ws [1]", status: "Permanent", support: "[RFC8323]", ref: "[RFC8323]", notes: "" },
    { scheme: "coaps", template: "", description: "coaps", status: "Permanent", support: "[RFC7252]", ref: "[RFC7252]", notes: "" },
    { scheme: "coaps+tcp", template: "", description: "coaps+tcp [1]", status: "Permanent", support: "[RFC8323]", ref: "[RFC8323]", notes: "" },
    { scheme: "coaps+ws", template: "", description: "coaps+ws [1]", status: "Permanent", support: "[RFC8323]", ref: "[RFC8323]", notes: "" },
    { scheme: "com-eventbrite-attendee", template: "prov/com-eventbrite-attendee", description: "com-eventbrite-attendee", status: "Provisional", support: "-", ref: "[Bob_Van_Zant]", notes: "" },
    { scheme: "content", template: "prov/content", description: "content", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "conti", template: "prov/conti", description: "conti", status: "Provisional", support: "-", ref: "[Michael_Hedenus]", notes: "" },
    { scheme: "crid", template: "", description: "TV-Anytime Content Reference Identifier", status: "Permanent", support: "-", ref: "[RFC4078]", notes: "" },
    { scheme: "cvs", template: "prov/cvs", description: "cvs", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "dab", template: "prov/dab", description: "dab", status: "Provisional", support: "-", ref: "[RadioDNS_Project]", notes: "" },
    { scheme: "dat", template: "prov/dat", description: "dat", status: "Provisional", support: "-", ref: "[Frédéric_Wang][Paul_Frazee]", notes: "" },
    { scheme: "data", template: "", description: "data", status: "Permanent", support: "-", ref: "[RFC2397]", notes: "" },
    { scheme: "dav", template: "", description: "dav", status: "Permanent", support: "-", ref: "[RFC4918]", notes: "" },
    { scheme: "diaspora", template: "prov/diaspora", description: "diaspora", status: "Provisional", support: "-", ref: "[Dennis_Schubert]", notes: "" },
    { scheme: "dict", template: "", description: "dictionary service protocol", status: "Permanent", support: "-", ref: "[RFC2229]", notes: "" },
    { scheme: "did", template: "prov/did", description: "did", status: "Provisional", support: "-", ref: "[W3C_Decentralized_Identifier_Working_Group ][Manu_Sporny][Ivan_Herman]", notes: "" },
    { scheme: "dis", template: "prov/dis", description: "dis", status: "Provisional", support: "-", ref: "[Christophe_Meessen]", notes: "" },
    { scheme: "dlna-playcontainer", template: "prov/dlna-playcontainer", description: "dlna-playcontainer", status: "Provisional", support: "-", ref: "[DLNA]", notes: "" },
    { scheme: "dlna-playsingle", template: "prov/dlna-playsingle", description: "dlna-playsingle", status: "Provisional", support: "-", ref: "[DLNA]", notes: "" },
    { scheme: "dns", template: "", description: "Domain Name System", status: "Permanent", support: "-", ref: "[RFC4501]", notes: "" },
    { scheme: "dntp", template: "prov/dntp", description: "dntp", status: "Provisional", support: "-", ref: "[Hans-Dieter_A._Hiep]", notes: "" },
    { scheme: "doi", template: "prov/doi", description: "doi", status: "Provisional", support: "-", ref: "[Frédéric_Wang][International_DOI_Foundation]", notes: "" },
    { scheme: "dpp", template: "prov/dpp", description: "dpp", status: "Provisional", support: "-", ref: "[Gaurav_Jain][Wi-Fi_Alliance]", notes: "" },
    { scheme: "drm", template: "prov/drm", description: "drm", status: "Provisional", support: "-", ref: "[RadioDNS_Project]", notes: "" },
    { scheme: "drop", template: "prov/drop", description: "drop", status: "Provisional", support: "-", ref: "[Tim_McSweeney]", notes: "" },
    { scheme: "dtmi", template: "prov/dtmi", description: "dtmi", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "dtn", template: "", description: "DTNRG research and development", status: "Provisional", support: "-", ref: "[RFC5050]", notes: "" },
    { scheme: "dvb", template: "", description: "dvb", status: "Provisional", support: "-", ref: "[draft-mcroberts-uri-dvb]", notes: "" },
    { scheme: "dweb", template: "prov/dweb", description: "dweb", status: "Provisional", support: "-", ref: "[Frédéric_Wang][Protocol_Labs]", notes: "" },
    { scheme: "ed2k", template: "prov/ed2k", description: "ed2k", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "elsi", template: "prov/elsi", description: "elsi", status: "Provisional", support: "-", ref: "[Kimmo_Lindholm]", notes: "" },
    { scheme: "ens", template: "prov/ens", description: "ens", status: "Provisional", support: "-", ref: "[Ricky_Bloomfield][Bradley_Nelson]", notes: "" },
    { scheme: "ethereum", template: "prov/ethereum", description: "ethereum", status: "Provisional", support: "-", ref: "[Frédéric_Wang][ligi]", notes: "" },
    { scheme: "example", template: "", description: "example", status: "Permanent", support: "-", ref: "[RFC7595]", notes: "" },
    { scheme: "facetime", template: "prov/facetime", description: "facetime", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "fax", template: "", description: "fax", status: "Historical", support: "-", ref: "[RFC2806][RFC3966]", notes: "" },
    { scheme: "feed", template: "prov/feed", description: "feed", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "feedready", template: "prov/feedready", description: "feedready", status: "Provisional", support: "-", ref: "[Mirko_Nosenzo]", notes: "" },
    { scheme: "file", template: "", description: "Host-specific file names", status: "Permanent", support: "-", ref: "[RFC8089]", notes: "" },
    { scheme: "filesystem", template: "historic/filesystem", description: "filesystem", status: "Historical", support: "-", ref: "[W3C_WebApps_Working_Group][Chris_Rebert]", notes: "" },
    { scheme: "finger", template: "prov/finger", description: "finger", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "first-run-pen-experience", template: "prov/first-run-pen-experience", description: "first-run-pen-experience", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "fish", template: "prov/fish", description: "fish", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "fm", template: "prov/fm", description: "fm", status: "Provisional", support: "-", ref: "[RadioDNS_Project]", notes: "" },
    { scheme: "ftp", template: "", description: "File Transfer Protocol", status: "Permanent", support: "-", ref: "[RFC1738]", notes: "" },
    { scheme: "fuchsia-pkg", template: "prov/fuchsia-pkg", description: "fuchsia-pkg", status: "Provisional", support: "-", ref: "[Adam_Barth][https://fuchsia.googlesource.com/fuchsia/]", notes: "" },
    { scheme: "geo", template: "", description: "Geographic Locations", status: "Permanent", support: "-", ref: "[RFC5870]", notes: "" },
    { scheme: "gg", template: "prov/gg", description: "gg", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "git", template: "prov/git", description: "git", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "gizmoproject", template: "prov/gizmoproject", description: "gizmoproject", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "go", template: "", description: "go", status: "Permanent", support: "-", ref: "[RFC3368]", notes: "" },
    { scheme: "gopher", template: "", description: "The Gopher Protocol", status: "Permanent", support: "-", ref: "[RFC4266]", notes: "" },
    { scheme: "graph", template: "prov/graph", description: "graph", status: "Provisional", support: "-", ref: "[Alastair_Green]", notes: "" },
    { scheme: "gtalk", template: "prov/gtalsk", description: "gtalk", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "h323", template: "", description: "H.323", status: "Permanent", support: "-", ref: "[RFC3508]", notes: "" },
    { scheme: "ham", template: "", description: "ham", status: "Provisional", support: "-", ref: "[RFC7046]", notes: "" },
    { scheme: "hcap", template: "prov/hcap", description: "hcap", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "hcp", template: "prov/hcp", description: "hcp", status: "Provisional", support: "-", ref: "[Alexey_Melnikov]", notes: "" },
    { scheme: "hxxp", template: "prov/hxxp", description: "hxxp", status: "Provisional", support: "-", ref: "[draft-salgado-hxxp]", notes: "" },
    { scheme: "hxxps", template: "prov/hxxps", description: "hxxps", status: "Provisional", support: "-", ref: "[draft-salgado-hxxp]", notes: "" },
    { scheme: "hydrazone", template: "", description: "hydrazone", status: "Provisional", support: "-", ref: "[Matthias_Merkel][https://tech.hydrazone.pro/uri/specification/hydrazone.txt]", notes: "" },
    { scheme: "hyper", template: "prov/hyper", description: "hyper", status: "Provisional", support: "-", ref: "[Frédéric_Wang][Paul_Frazee]", notes: "" },
    { scheme: "iax", template: "", description: "Inter-Asterisk eXchange Version 2", status: "Permanent", support: "-", ref: "[RFC5456]", notes: "" },
    { scheme: "icap", template: "", description: "Internet Content Adaptation Protocol", status: "Permanent", support: "-", ref: "[RFC3507]", notes: "" },
    { scheme: "icon", template: "", description: "icon", status: "Provisional", support: "-", ref: "[draft-lafayette-icon-uri-scheme]", notes: "" },
    { scheme: "im", template: "", description: "Instant Messaging", status: "Permanent", support: "-", ref: "[RFC3860]", notes: "" },
    { scheme: "imap", template: "", description: "internet message access protocol", status: "Permanent", support: "-", ref: "[RFC5092]", notes: "" },
    { scheme: "info", template: "", description: "Information Assets with Identifiers in Public Namespaces. [RFC4452] (section 3) defines an \"info\" registry of public namespaces, which is maintained by NISO and can be accessed from [http://info-uri.info/].", status: "Permanent", support: "-", ref: "[RFC4452]", notes: "" },
    { scheme: "iotdisco", template: "prov/iotdisco", description: "iotdisco", status: "Provisional", support: "-", ref: "[Peter_Waher][http://www.iana.org/assignments/uri-schemes/prov/iotdisco.pdf]", notes: "" },
    { scheme: "ipfs", template: "prov/ipfs", description: "ipfs", status: "Provisional", support: "-", ref: "[Frédéric_Wang][Protocol_Labs]", notes: "" },
    { scheme: "ipn", template: "", description: "ipn", status: "Provisional", support: "-", ref: "[RFC6260]", notes: "" },
    { scheme: "ipns", template: "prov/ipns", description: "ipns", status: "Provisional", support: "-", ref: "[Frédéric_Wang][Protocol_Labs]", notes: "" },
    { scheme: "ipp", template: "", description: "Internet Printing Protocol", status: "Permanent", support: "-", ref: "[RFC3510]", notes: "" },
    { scheme: "ipps", template: "", description: "Internet Printing Protocol over HTTPS", status: "Permanent", support: "-", ref: "[RFC7472]", notes: "" },
    { scheme: "irc", template: "prov/irc", description: "irc", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "irc6", template: "prov/irc6", description: "irc6", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "ircs", template: "prov/ircs", description: "ircs", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "iris", template: "", description: "Internet Registry Information Service", status: "Permanent", support: "-", ref: "[RFC3981]", notes: "" },
    { scheme: "iris.beep", template: "", description: "iris.beep", status: "Permanent", support: "-", ref: "[RFC3983]", notes: "" },
    { scheme: "iris.lwz", template: "", description: "iris.lwz", status: "Permanent", support: "-", ref: "[RFC4993]", notes: "" },
    { scheme: "iris.xpc", template: "", description: "iris.xpc", status: "Permanent", support: "-", ref: "[RFC4992]", notes: "" },
    { scheme: "iris.xpcs", template: "", description: "iris.xpcs", status: "Permanent", support: "-", ref: "[RFC4992]", notes: "" },
    { scheme: "isostore", template: "prov/isostore", description: "isostore", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "itms", template: "prov/itms", description: "itms", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "jabber", template: "perm/jabber", description: "jabber", status: "Permanent", support: "-", ref: "[Peter_Saint-Andre]", notes: "" },
    { scheme: "jar", template: "prov/jar", description: "jar", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "jms", template: "", description: "Java Message Service", status: "Provisional", support: "-", ref: "[RFC6167]", notes: "" },
    { scheme: "keyparc", template: "prov/keyparc", description: "keyparc", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "lastfm", template: "prov/lastfm", description: "lastfm", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "lbry", template: "prov/lbry", description: "lbry", status: "Provisional", support: "-", ref: "[Alex_Grintsvayg]", notes: "" },
    { scheme: "ldap", template: "", description: "Lightweight Directory Access Protocol", status: "Permanent", support: "-", ref: "[RFC4516]", notes: "" },
    { scheme: "ldaps", template: "prov/ldaps", description: "ldaps", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "leaptofrogans", template: "", description: "leaptofrogans", status: "Permanent", support: "-", ref: "[RFC8589]", notes: "" },
    { scheme: "lorawan", template: "prov/lorawan", description: "lorawan", status: "Provisional", support: "-", ref: "[OMA-DMSE]", notes: "" },
    { scheme: "lvlt", template: "prov/lvlt", description: "lvlt", status: "Provisional", support: "-", ref: "[Alexander_Shishenko]", notes: "" },
    { scheme: "magnet", template: "prov/magnet", description: "magnet", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "mailserver", template: "", description: "Access to data available from mail servers", status: "Historical", support: "-", ref: "[RFC6196]", notes: "" },
    { scheme: "mailto", template: "", description: "Electronic mail address", status: "Permanent", support: "-", ref: "[RFC6068]", notes: "" },
    { scheme: "maps", template: "prov/maps", description: "maps", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "market", template: "prov/market", description: "market", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "matrix", template: "prov/matrix", description: "matrix", status: "Provisional", support: "-", ref: "[Hubert_Chathi]", notes: "" },
    { scheme: "message", template: "prov/message", description: "message", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "microsoft.windows.camera", template: "prov/microsoft.windows.camera", description: "microsoft.windows.camera", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "microsoft.windows.camera.multipicker", template: "prov/microsoft.windows.camera.multipicker", description: "microsoft.windows.camera.multipicker", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "microsoft.windows.camera.picker", template: "prov/microsoft.windows.camera.picker", description: "microsoft.windows.camera.picker", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "mid", template: "", description: "message identifier", status: "Permanent", support: "-", ref: "[RFC2392]", notes: "" },
    { scheme: "mms", template: "prov/mms", description: "mms", status: "Provisional", support: "-", ref: "[Alexey_Melnikov]", notes: "" },
    { scheme: "modem", template: "", description: "modem", status: "Historical", support: "-", ref: "[RFC2806][RFC3966]", notes: "" },
    { scheme: "mongodb", template: "prov/mongodb", description: "mongodb", status: "Provisional", support: "-", ref: "[Ignacio_Losiggio][Mongo_DB_Inc]", notes: "" },
    { scheme: "moz", template: "prov/moz", description: "moz", status: "Provisional", support: "-", ref: "[Joe_Hildebrand]", notes: "" },
    { scheme: "ms-access", template: "prov/ms-access", description: "ms-access", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-browser-extension", template: "prov/ms-browser-extension", description: "ms-browser-extension", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-calculator", template: "prov/ms-calculator", description: "ms-calculator", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-drive-to", template: "prov/ms-drive-to", description: "ms-drive-to", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-enrollment", template: "prov/ms-enrollment", description: "ms-enrollment", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-excel", template: "prov/ms-excel", description: "ms-excel", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-eyecontrolspeech", template: "prov/ms-eyecontrolspeech", description: "ms-eyecontrolspeech", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-gamebarservices", template: "prov/ms-gamebarservices", description: "ms-gamebarservices", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-gamingoverlay", template: "prov/ms-gamingoverlay", description: "ms-gamingoverlay", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-getoffice", template: "prov/ms-getoffice", description: "ms-getoffice", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-help", template: "prov/ms-help", description: "ms-help", status: "Provisional", support: "-", ref: "[Alexey_Melnikov]", notes: "" },
    { scheme: "ms-infopath", template: "prov/ms-infopath", description: "ms-infopath", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-inputapp", template: "prov/ms-inputapp", description: "ms-inputapp", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-lockscreencomponent-config", template: "prov/ms-lockscreencomponent-config", description: "ms-lockscreencomponent-config", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-media-stream-id", template: "prov/ms-media-stream-id", description: "ms-media-stream-id", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-mixedrealitycapture", template: "prov/ms-mixedrealitycapture", description: "ms-mixedrealitycapture", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-mobileplans", template: "prov/ms-mobileplans", description: "ms-mobileplans", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-officeapp", template: "prov/ms-officeapp", description: "ms-officeapp", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-people", template: "prov/ms-people", description: "ms-people", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-project", template: "prov/ms-project", description: "ms-project", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-powerpoint", template: "prov/ms-powerpoint", description: "ms-powerpoint", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-publisher", template: "prov/ms-publisher", description: "ms-publisher", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-restoretabcompanion", template: "prov/ms-restoretabcompanion", description: "ms-restoretabcompanion", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-screenclip", template: "prov/ms-screenclip", description: "ms-screenclip", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-screensketch", template: "prov/ms-screensketch", description: "ms-screensketch", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-search", template: "prov/ms-search", description: "ms-search", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-search-repair", template: "prov/ms-search-repair", description: "ms-search-repair", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-secondary-screen-controller", template: "prov/ms-secondary-screen-controller", description: "ms-secondary-screen-controller", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-secondary-screen-setup", template: "prov/ms-secondary-screen-setup", description: "ms-secondary-screen-setup", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-settings", template: "prov/ms-settings", description: "ms-settings", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-settings-airplanemode", template: "prov/ms-settings-airplanemode", description: "ms-settings-airplanemode", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-settings-bluetooth", template: "prov/ms-settings-bluetooth", description: "ms-settings-bluetooth", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-settings-camera", template: "prov/ms-settings-camera", description: "ms-settings-camera", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-settings-cellular", template: "prov/ms-settings-cellular", description: "ms-settings-cellular", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-settings-cloudstorage", template: "prov/ms-settings-cloudstorage", description: "ms-settings-cloudstorage", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-settings-connectabledevices", template: "prov/ms-settings-connectabledevices", description: "ms-settings-connectabledevices", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-settings-displays-topology", template: "prov/ms-settings-displays-topology", description: "ms-settings-displays-topology", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-settings-emailandaccounts", template: "prov/ms-settings-emailandaccounts", description: "ms-settings-emailandaccounts", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-settings-language", template: "prov/ms-settings-language", description: "ms-settings-language", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-settings-location", template: "prov/ms-settings-location", description: "ms-settings-location", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-settings-lock", template: "prov/ms-settings-lock", description: "ms-settings-lock", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-settings-nfctransactions", template: "prov/ms-settings-nfctransactions", description: "ms-settings-nfctransactions", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-settings-notifications", template: "prov/ms-settings-notifications", description: "ms-settings-notifications", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-settings-power", template: "prov/ms-settings-power", description: "ms-settings-power", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-settings-privacy", template: "prov/ms-settings-privacy", description: "ms-settings-privacy", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-settings-proximity", template: "prov/ms-settings-proximity", description: "ms-settings-proximity", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-settings-screenrotation", template: "prov/ms-settings-screenrotation", description: "ms-settings-screenrotation", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-settings-wifi", template: "prov/ms-settings-wifi", description: "ms-settings-wifi", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-settings-workplace", template: "prov/ms-settings-workplace", description: "ms-settings-workplace", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-spd", template: "prov/ms-spd", description: "ms-spd", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-sttoverlay", template: "prov/ms-sttoverlay", description: "ms-sttoverlay", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-transit-to", template: "prov/ms-transit-to", description: "ms-transit-to", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-useractivityset", template: "prov/ms-useractivityset", description: "ms-useractivityset", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-virtualtouchpad", template: "prov/ms-virtualtouchpad", description: "ms-virtualtouchpad", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-visio", template: "prov/ms-visio", description: "ms-visio", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-walk-to", template: "prov/ms-walk-to", description: "ms-walk-to", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-whiteboard", template: "prov/ms-whiteboard", description: "ms-whiteboard", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-whiteboard-cmd", template: "prov/ms-whiteboard-cmd", description: "ms-whiteboard-cmd", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "ms-word", template: "prov/ms-word", description: "ms-word", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "msnim", template: "prov/msnim", description: "msnim", status: "Provisional", support: "-", ref: "[Alexey_Melnikov]", notes: "" },
    { scheme: "msrp", template: "", description: "Message Session Relay Protocol", status: "Permanent", support: "-", ref: "[RFC4975]", notes: "" },
    { scheme: "msrps", template: "", description: "Message Session Relay Protocol Secure", status: "Permanent", support: "-", ref: "[RFC4975][RFC-ietf-mmusic-msrp-usage-data-channel-23]", notes: "" },
    { scheme: "mss", template: "prov/mss", description: "mss", status: "Provisional", support: "-", ref: "[Jarmo_Miettinen]", notes: "" },
    { scheme: "mtqp", template: "", description: "Message Tracking Query Protocol", status: "Permanent", support: "-", ref: "[RFC3887]", notes: "" },
    { scheme: "mumble", template: "prov/mumble", description: "mumble", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "mupdate", template: "", description: "Mailbox Update (MUPDATE) Protocol", status: "Permanent", support: "-", ref: "[RFC3656]", notes: "" },
    { scheme: "mvn", template: "prov/mvn", description: "mvn", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "news", template: "", description: "USENET news", status: "Permanent", support: "-", ref: "[RFC5538]", notes: "" },
    { scheme: "nfs", template: "", description: "network file system protocol", status: "Permanent", support: "-", ref: "[RFC2224]", notes: "" },
    { scheme: "ni", template: "", description: "ni", status: "Permanent", support: "-", ref: "[RFC6920]", notes: "" },
    { scheme: "nih", template: "", description: "nih", status: "Permanent", support: "-", ref: "[RFC6920]", notes: "" },
    { scheme: "nntp", template: "", description: "USENET news using NNTP access", status: "Permanent", support: "-", ref: "[RFC5538]", notes: "" },
    { scheme: "notes", template: "prov/notes", description: "notes", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "num", template: "prov/num", description: "Namespace Utility Modules", status: "Provisional", support: "-", ref: "[Elliott_Brown][https://www.numprotocol.com/specification]", notes: "" },
    { scheme: "ocf", template: "prov/ocf", description: "ocf", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "oid", template: "prov/oid", description: "oid", status: "Provisional", support: "-", ref: "[draft-larmouth-oid-iri]", notes: "" },
    { scheme: "onenote", template: "prov/onenote", description: "onenote", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "onenote-cmd", template: "prov/onenote-cmd", description: "onenote-cmd", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "opaquelocktoken", template: "", description: "opaquelocktokent", status: "Permanent", support: "-", ref: "[RFC4918]", notes: "" },
    { scheme: "openpgp4fpr", template: "prov/openpgp4fpr", description: "openpgp4fpr", status: "Provisional", support: "-", ref: "[Wiktor_Kwapisiewicz]", notes: "" },
    { scheme: "otpauth", template: "prov/otpauth", description: "otpauth", status: "Provisional", support: "-", ref: "[Frédéric_Wang][Thomas_Habets]", notes: "" },
    { scheme: "pack", template: "historic/pack", description: "pack", status: "Historical", support: "-", ref: "[draft-shur-pack-uri-scheme]", notes: "" },
    { scheme: "palm", template: "prov/palm", description: "palm", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "paparazzi", template: "prov/paparazzi", description: "paparazzi", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "payment", template: "prov/payment", description: "payment", status: "Provisional", support: "-", ref: "[Arild_Hegvik][https://bitcoincheque.org]", notes: "" },
    { scheme: "payto", template: "prov/payto", description: "payto", status: "Provisional", support: "-", ref: "[RFC8905]", notes: "" },
    { scheme: "pkcs11", template: "", description: "PKCS#11", status: "Permanent", support: "-", ref: "[RFC7512]", notes: "" },
    { scheme: "platform", template: "prov/platform", description: "platform", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "pop", template: "", description: "Post Office Protocol v3", status: "Permanent", support: "-", ref: "[RFC2384]", notes: "" },
    { scheme: "pres", template: "", description: "Presence", status: "Permanent", support: "-", ref: "[RFC3859]", notes: "" },
    { scheme: "prospero", template: "", description: "Prospero Directory Service", status: "Historical", support: "-", ref: "[RFC4157]", notes: "" },
    { scheme: "proxy", template: "prov/proxy", description: "proxy", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "pwid", template: "prov/pwid", description: "pwid", status: "Provisional", support: "-", ref: "[Eld_Zierau]", notes: "" },
    { scheme: "psyc", template: "prov/psyc", description: "psyc", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "pttp", template: "prov/pttp", description: "pttp", status: "Provisional", support: "-", ref: "[Tony_Deng][Tuan_Hoang][Bob_Hinkle][Mark_Chen]", notes: "" },
    { scheme: "qb", template: "prov/qb", description: "qb", status: "Provisional", support: "-", ref: "[Jan_Pokorny]", notes: "" },
    { scheme: "query", template: "prov/query", description: "query", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "quic-transport", template: "prov/quic-transport", description: "quic-transport", status: "Provisional", support: "-", ref: "[draft-vvv-webtransport-quic]", notes: "" },
    { scheme: "redis", template: "prov/redis", description: "redis", status: "Provisional", support: "-", ref: "[Chris_Rebert]", notes: "" },
    { scheme: "rediss", template: "prov/rediss", description: "rediss", status: "Provisional", support: "-", ref: "[Chris_Rebert]", notes: "" },
    { scheme: "reload", template: "", description: "reload", status: "Permanent", support: "-", ref: "[RFC6940]", notes: "" },
    { scheme: "res", template: "prov/res", description: "res", status: "Provisional", support: "-", ref: "[Alexey_Melnikov]", notes: "" },
    { scheme: "resource", template: "prov/resource", description: "resource", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "rmi", template: "prov/rmi", description: "rmi", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "rsync", template: "", description: "rsync", status: "Provisional", support: "-", ref: "[RFC5781]", notes: "" },
    { scheme: "rtmfp", template: "prov/rtmfp", description: "rtmfp", status: "Provisional", support: "-", ref: "[RFC7425]", notes: "" },
    { scheme: "rtmp", template: "prov/rtmp", description: "rtmp", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "rtsp", template: "", description: "Real-Time Streaming Protocol (RTSP)", status: "Permanent", support: "-", ref: "[RFC2326][RFC7826]", notes: "" },
    { scheme: "rtsps", template: "", description: "Real-Time Streaming Protocol (RTSP) over TLS", status: "Permanent", support: "-", ref: "[RFC2326][RFC7826]", notes: "" },
    { scheme: "rtspu", template: "", description: "Real-Time Streaming Protocol (RTSP) over unreliable datagram transport", status: "Permanent", support: "-", ref: "[RFC2326]", notes: "" },
    { scheme: "secondlife", template: "prov/secondlife", description: "query", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "secret-token", template: "prov/secret-token", description: "secret-token", status: "Provisional", support: "-", ref: "[RFC-nottingham-how-did-that-get-into-the-repo-02]", notes: "" },
    { scheme: "service", template: "", description: "service location", status: "Permanent", support: "-", ref: "[RFC2609]", notes: "" },
    { scheme: "session", template: "", description: "session", status: "Permanent", support: "-", ref: "[RFC6787]", notes: "" },
    { scheme: "sftp", template: "prov/sftp", description: "query", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "sgn", template: "prov/sgn", description: "sgn", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "shttp", template: "", description: "Secure Hypertext Transfer Protocol", status: "Permanent", support: "-", ref: "[RFC2660]", notes: "" },
    { scheme: "sieve", template: "", description: "ManageSieve Protocol", status: "Permanent", support: "-", ref: "[RFC5804]", notes: "" },
    { scheme: "simpleledger", template: "prov/simpleledger", description: "simpleledger", status: "Provisional", support: "-", ref: "[James_Cramer]", notes: "" },
    { scheme: "sip", template: "", description: "session initiation protocol", status: "Permanent", support: "-", ref: "[RFC3261]", notes: "" },
    { scheme: "sips", template: "", description: "secure session initiation protocol", status: "Permanent", support: "-", ref: "[RFC3261]", notes: "" },
    { scheme: "skype", template: "prov/skype", description: "skype", status: "Provisional", support: "-", ref: "[Alexey_Melnikov]", notes: "" },
    { scheme: "smb", template: "prov/smb", description: "smb", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "sms", template: "", description: "Short Message Service", status: "Permanent", support: "-", ref: "[RFC5724]", notes: "" },
    { scheme: "smtp", template: "prov/smtp", description: "smtp", status: "Provisional", support: "-", ref: "[draft-melnikov-smime-msa-to-mda]", notes: "" },
    { scheme: "snews", template: "", description: "NNTP over SSL/TLS", status: "Historical", support: "-", ref: "[RFC5538]", notes: "" },
    { scheme: "snmp", template: "", description: "Simple Network Management Protocol", status: "Permanent", support: "-", ref: "[RFC4088]", notes: "" },
    { scheme: "soap.beep", template: "", description: "soap.beep", status: "Permanent", support: "-", ref: "[RFC4227]", notes: "" },
    { scheme: "soap.beeps", template: "", description: "soap.beeps", status: "Permanent", support: "-", ref: "[RFC4227]", notes: "" },
    { scheme: "soldat", template: "prov/soldat", description: "soldat", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "spiffe", template: "prov/spiffe", description: "spiffe", status: "Provisional", support: "-", ref: "[Evan_Gilman]", notes: "" },
    { scheme: "spotify", template: "prov/spotify", description: "spotify", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "ssb", template: "prov/ssb", description: "ssb", status: "Provisional", support: "-", ref: "[Frédéric_Wang][Secure_Scuttlebutt_Consortium]", notes: "" },
    { scheme: "ssh", template: "prov/ssh", description: "ssh", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "steam", template: "prov/steam", description: "steam", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "stun", template: "", description: "stun", status: "Permanent", support: "-", ref: "[RFC7064]", notes: "" },
    { scheme: "stuns", template: "", description: "stuns", status: "Permanent", support: "-", ref: "[RFC7064]", notes: "" },
    { scheme: "submit", template: "prov/submit", description: "submit", status: "Provisional", support: "-", ref: "[draft-melnikov-smime-msa-to-mda]", notes: "" },
    { scheme: "swh", template: "prov/swh", description: "swh", status: "Provisional", support: "-", ref: "[Software_Heritage][Stefano_Zacchiroli]", notes: "" },
    { scheme: "svn", template: "prov/svn", description: "svn", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "tag", template: "", description: "tag", status: "Permanent", support: "-", ref: "[RFC4151]", notes: "" },
    { scheme: "teamspeak", template: "prov/teamspeak", description: "teamspeak", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "teliaeid", template: "prov/teliaeid", description: "teliaeid", status: "Provisional", support: "-", ref: "[Peter_Lewandowski]", notes: "" },
    { scheme: "telnet", template: "", description: "Reference to interactive sessions", status: "Permanent", support: "-", ref: "[RFC4248]", notes: "" },
    { scheme: "tftp", template: "", description: "Trivial File Transfer Protocol", status: "Permanent", support: "-", ref: "[RFC3617]", notes: "" },
    { scheme: "things", template: "prov/things", description: "things", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "thismessage", template: "perm/thismessage", description: "multipart/related relative reference resolution", status: "Permanent", support: "-", ref: "[RFC2557]", notes: "" },
    { scheme: "tip", template: "", description: "Transaction Internet Protocol", status: "Permanent", support: "-", ref: "[RFC2371]", notes: "" },
    { scheme: "tn3270", template: "", description: "Interactive 3270 emulation sessions", status: "Permanent", support: "-", ref: "[RFC6270]", notes: "" },
    { scheme: "tool", template: "prov/tool", description: "tool", status: "Provisional", support: "-", ref: "[Matthias_Merkel]", notes: "" },
    { scheme: "turn", template: "", description: "turn", status: "Permanent", support: "-", ref: "[RFC7065]", notes: "" },
    { scheme: "turns", template: "", description: "turns", status: "Permanent", support: "-", ref: "[RFC7065]", notes: "" },
    { scheme: "tv", template: "", description: "TV Broadcasts", status: "Permanent", support: "-", ref: "[RFC2838]", notes: "" },
    { scheme: "udp", template: "prov/udp", description: "udp", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "unreal", template: "prov/unreal", description: "unreal", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "upt", template: "prov/upt", description: "upt", status: "Provisional", support: "-", ref: "[Tim_McSweeney]", notes: "" },
    { scheme: "urn", template: "", description: "Uniform Resource Names", status: "Permanent", support: "-", ref: "[RFC8141][IANA registry urn-namespaces]", notes: "" },
    { scheme: "ut2004", template: "prov/ut2004", description: "ut2004", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "v-event", template: "prov/v-event", description: "v-event", status: "Provisional", support: "-", ref: "[draft-menderico-v-event-uri]", notes: "" },
    { scheme: "vemmi", template: "", description: "versatile multimedia interface", status: "Permanent", support: "-", ref: "[RFC2122]", notes: "" },
    { scheme: "ventrilo", template: "prov/ventrilo", description: "ventrilo", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "videotex", template: "historic/videotex", description: "videotex", status: "Historical", support: "-", ref: "[draft-mavrakis-videotex-url-spec][RFC2122][RFC3986]", notes: "" },
    { scheme: "vnc", template: "", description: "Remote Framebuffer Protocol", status: "Permanent", support: "-", ref: "[RFC7869]", notes: "" },
    { scheme: "view-source", template: "prov/view-source", description: "view-source", status: "Provisional", support: "-", ref: "[Mykyta_Yevstifeyev]", notes: "" },
    { scheme: "vscode", template: "prov/vscode", description: "vscode", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "vscode-insiders", template: "prov/vscode-insiders", description: "vscode-insiders", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "vsls", template: "prov/vsls", description: "vsls", status: "Provisional", support: "-", ref: "[urischemeowners_at_microsoft.com]", notes: "" },
    { scheme: "wais", template: "", description: "Wide Area Information Servers", status: "Historical", support: "-", ref: "[RFC4156]", notes: "" },
    { scheme: "wcr", template: "prov/wcr", description: "wcr", status: "Provisional", support: "-", ref: "[Jason_Dzubak]", notes: "" },
    { scheme: "webcal", template: "prov/webcal", description: "webcal", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "wifi", template: "prov/wifi", description: "wifi", status: "Provisional", support: "-", ref: "[Wi-Fi_Alliance][Jun_Tian]", notes: "" },
    { scheme: "wpid", template: "prov/wpid", description: "wpid", status: "Historical", support: "-", ref: "[Eld_Zierau]", notes: "" },
    { scheme: "ws", template: "", description: "WebSocket connections", status: "Permanent", support: "[RFC8307]", ref: "[RFC6455]", notes: "" },
    { scheme: "wss", template: "", description: "Encrypted WebSocket connections", status: "Permanent", support: "[RFC8307]", ref: "[RFC6455]", notes: "" },
    { scheme: "wtai", template: "prov/wtai", description: "wtai", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "wyciwyg", template: "prov/wyciwyg", description: "wyciwyg", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "xcon", template: "", description: "xcon", status: "Permanent", support: "-", ref: "[RFC6501]", notes: "" },
    { scheme: "xcon-userid", template: "", description: "xcon-userid", status: "Permanent", support: "-", ref: "[RFC6501]", notes: "" },
    { scheme: "xfire", template: "prov/xfire", description: "xfire", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "xmlrpc.beep", template: "", description: "xmlrpc.beep", status: "Permanent", support: "-", ref: "[RFC3529]", notes: "" },
    { scheme: "xmlrpc.beeps", template: "", description: "xmlrpc.beeps", status: "Permanent", support: "-", ref: "[RFC3529]", notes: "" },
    { scheme: "xmpp", template: "", description: "Extensible Messaging and Presence Protocol", status: "Permanent", support: "-", ref: "[RFC5122]", notes: "" },
    { scheme: "xri", template: "prov/xri", description: "xri", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "ymsgr", template: "prov/ymsgr", description: "ymsgr", status: "Provisional", support: "-", ref: "[Dave_Thaler]", notes: "" },
    { scheme: "z39.50", template: "", description: "Z39.50 information access", status: "Historical", support: "-", ref: "[RFC1738][RFC2056]", notes: "" },
    { scheme: "z39.50r", template: "", description: "Z39.50 Retrieval", status: "Permanent", support: "-", ref: "[RFC2056]", notes: "" },
    { scheme: "z39.50s", template: "", description: "Z39.50 Session", status: "Permanent", support: "-", ref: "[RFC2056]", notes: "" }
  ]
}]
